development:
  secret_key_base: # Run $ rake secret and paste here the result
  twitter_api_key: # Twitter Consumer Key (API Key)  
  twitter_api_secret: # Twitter Consumer Secret (API Secret)
test:
  secret_key_base: # Run $ rake secret and paste here the result

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>